version: '3.6'
services:
  kratos-migrate:
    image: oryd/kratos:v0.9.0-alpha.3
    environment:
      - DSN=postgres://postgres:secretpgpassword@postgres:5432/sifty
    command: -c /config/kratos/config.yaml migrate sql -e --yes
    restart: on-failure
    volumes:
      - ./ory/kratos:/config/kratos
    depends_on:
      - postgres
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.9.0-alpha.3
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      DSN: postgres://postgres:secretpgpassword@postgres:5432/sifty
      LOG_LEVEL: trace
      SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_0_MAPPER_URL: file:///config/kratos/oidc.google.jsonnet
    command: serve -c /config/kratos/config.yaml -c /config/kratos/config.dev.yaml --dev --watch-courier
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./ory/kratos:/config/kratos
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
  oathkeeper:
    image: oryd/oathkeeper:v0.38
    ports:
      - "4455:4455"
      - "4456:4456"
    command: '--config /config/oathkeeper/config.yaml serve'
    environment:
      ACCESS_RULES_REPOSITORIES: file:///config/oathkeeper/rules.yaml,file:///config/oathkeeper/rules.frontend.yaml
      MUTATORS_ID_TOKEN_CONFIG_JWKS_URL: file:///config/oathkeeper/jwks.json
    volumes:
      - "./ory/oathkeeper:/config/oathkeeper"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  hasura:
    image: hasura/graphql-engine:v2.4.0
    depends_on:
    - postgres
    restart: always
    environment:
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      HASURA_GRAPHQL_LOG_LEVEL: debug
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_METADATA_DIRECTORY: /config/hasura/metadata
      HASURA_GRAPHQL_MIGRATIONS_DIRECTORY: /config/hasura/migrations
      BACKEND_GRAPHQL_ENDPOINT: http://oathkeeper:4455/api/backend/v1/graphql
    volumes:
      - "./hasura:/config/hasura"
    env_file:
    - .env
    ports:
    - '8080:8080'
    labels:
      kompose.service.expose: "api.getsifty.com"
      kompose.service.expose.tls-secret: "cookwherever-com-tls"